services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=senha
    ports:
      - "5679:5678"  # alterado para evitar conflito
    volumes:
      - ./n8n-data:/home/node/.n8n
