services:
  n8n:
    build: .
    container_name: n8n-playwright
    restart: unless-stopped
    ports:
      - "8080:5678" # <- Porta externa 8080
    volumes:
      - n8n_data:/home/nodeuser/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - TZ=America/Sao_Paulo
    tty: true

volumes:
  n8n_data:
